[package]
name = "tbd"
version = "0.1.0"
edition = "2018"

[dependencies]
ureq = "1.3.0"
png = "0.16.6"

[workspace]
members = [".", "scratches/*"]

[profile.release]
lto = true

[lib]
doctest = false
